### ISSUE TITLE
Task: Make primary cell class

### ISSUE THREAD

**Issue by tirth132** [tirth132/game-engine#2]
Task: Primary implementation of `Cell` class which represents cells on board

## Description
The class `Cell` represents cells on board(game window). Primary implementation will include x and y axis of cell on board. Improvements will be done later after primary implementation. 

## Task requires
- [ ] A class called `Cell` must be found in `com.dino.cell` package.
- [ ] Class should have two immutable(final) ints to store x and y axis.
- [ ] A constructor initialising both axis is necessary.
- [ ] Constructor should be checking for validity of axis(negative axis aren't allowed).
- [ ] Class should have getters for both axis.

Issue can be closed after passing test case testing for requirement.

**Comment by tirth132** [comment]
Test cases added by commit b9e2be705bd9a68b3bf668072689088be9cb7aa3 test all requirements. So i can go with this implementation.

**Comment by tirth132** [comment]
Cell class passes test case and is ready to be merged.
