### ISSUE TITLE
Task: Add cell colors

### ISSUE THREAD

**Issue by tirth132** [tirth132/game-engine#3]
# Task: Add cell colors
Games need colorful cells to make background 
beautiful. Make a way for cells to be identified 
their color.

- [ ] The work should be done on `imp-game-objects` branch.
- [ ] A class called `CellColor` must be placed 
inside `com.dino.cell` package.
- [ ] CellColor should have three immutable ints for storing RGB values.
- [ ]  Constructor should initialize RGB values and  throw exception if RGB value is invalid.
- [ ]  Class should have getters for all three RGB values.

Issue can be closed after passing appropriate test case.
